alfabetoc = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ"

cifradoc = "SI CUPDMZAPLIL UIKPWUIS ICBWUWTI LM TMFPKW OI LMAMTXMVILW CU XIXMS XZWBIÑWUPKW MU SI OPABWZPI G MU SI NWZTIKPWU LM UCMABZW XIPA. SIA BIZMIA ACABIUBPDIA LM MABI PUABPBCKPWU XCJSPKI, ICBWUWTI G SIPKI AWU SI LWKMUKPI, SI PUDMABPÑIKPWU G SI LPNCAPWU LM SI KCSBCZI. MU MS TCULW IKILMTPKW MA ZMKWUWKPLI KWTW CUI CUPDMZAPLIL LM MFKMSMUKPI. SI CUIT ZMAXWULM IS XZMAMUBM G TPZI MS NCBCZW KWTW MS XZWGMKBW KCSBCZIS TIA PTXWZBIUBM LM TMFPKW. SI CUIT MA CU MAXIKPW LM SPJMZBILMA. MU MSSI AM XZIKBPKI KWBPLPIUITMUBM MS ZMAXMBW, SI BWSMZIUKPI G MS LPISWÑW. SI XSCZISPLIL LM PLMIA G LM XMUAITPMUBW MA IXZMKPILI KWTW APÑUW LM AC ZPYCMHI G UCUKI KWTW NIKBWZ LM LMJPSPLIL."

for clavec in range(1, len(alfabetoc)):

    mensaje = ""

    for let in cifradoc.upper():
        if let in alfabetoc:
            ind = alfabetoc.find(let)
            ind -= clavec
            if ind < 0:
                ind += 27
            mensaje += alfabetoc[ind]
        else:
            mensaje += let

    print (f"Clave: {clavec} - {mensaje}")
